---
dependency:
  name: 'galaxy'
driver:
  name: 'vagrant'
  provider:
    name: 'virtualbox'
platforms:
  - name: 'moleculerh7'
    box: 'RHEL7'
    box_url: 'https://auto-tests.pro.icp-2.intranet.cloud.test.es/repository/vagrant-boxes/RHEL-7.5.box'
    instance_raw_config_args:
      - "ssh.insert_key = false"
    config_options:
      vm.box_download_insecure: true
    memory: 2048
    cpus: 1
provisioner:
  name: 'ansible'
  inventory:
    host_vars:
      moleculerh7:
        ansible_user: 'vagrant'

verifier:
  name: 'ansible'

scenario:
  test_sequence:
    # - 'dependency'
    # - 'lint'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    - 'idempotence'
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
